### ISSUE TITLE
Glibc error when using Cuckoo 2.0.3: Cannot find 'Glibc' in scope

### ISSUE THREAD

**Issue by aiKrice** [Brightify/Cuckoo#496]
Hello when I tried Cuckoo v2 in alpha, I had the same issue. Now, I want to try again but still face the same issue:

Cannot find 'Glibc' in scope in the XcodeProj Dependency.

So I tried a dummy project, same error so I would like to know if you have any hint ?
I can send my dummy project in attachment if needed. 

I really want to use this new version !

**Comment by MatyasKriz** [comment]
Hey, I was trying to get more information in that thread, but was unable to do so. Please send the dummy project along with some info about the Xcode you're using as I was unable to reproduce this issue.

**Comment by aiKrice** [comment]
Hello there. Please find the test project which has the error in attachment
[Chriscukoo.zip](https://github.com/user-attachments/files/15586963/Chriscukoo.zip)

**Comment by MatyasKriz** [comment]
Thanks, unfortunately I still don't have access to internet but I'll take a look at this as soon as I can.

**Comment by aiKrice** [comment]
Alright 👍

**Comment by aiKrice** [comment]
Up @MatyasKriz

**Comment by MatyasKriz** [comment]
> Up @MatyasKriz 

up?

**Comment by aiKrice** [comment]
It was to wake up you, if you had the chance to have a look into

**Comment by MatyasKriz** [comment]
> It was to wake up you, if you had the chance to have a look into

Nope, I still don't have internet set up at home, so I have more pressing issues. However, I'd happily merge a fix for this.

**Comment by MatyasKriz** [comment]
I found out the issue. It's that Xcodeproj is not meant for iOS: https://github.com/tuist/XcodeProj/issues/817

I'll see what I can do about that.

**Comment by MatyasKriz** [comment]
Okay, so the problem is with the configuration. You aren't supposed to include `CuckooGenerator` in the project. Only `Cuckoo`.

And the Cuckoofile.toml is obviously copied from the repository instead of created with the help of README. If you need help, please create an issue. I've fixed it into this:

```toml
[modules.Chriscukoo]
imports = ["Foundation"]
testableImports = ["Chriscukoo"]
sources = [
    "Tests/Swift/Source/*.swift",
]
exclude = []
# regex = ""
output = "Tests/Swift/Generated/GeneratedMocks.swift"

[modules.Chriscukoo.options]
glob = true
keepDocumentation = false

[modules.Chriscukoo.xcodeproj]
path = "."
target = "Chriscukoo"
```

I'll try to make some changes so the configuration file is easier to use either way.
